Update modeling3d.html
Sunwart/39-team12-freedom3d pull request #10
Opened 2021-08-13 19:41 UTC by Vsevolod1001

внес разметку html, возможно некоторые классы переименую, когда запушат переменные, на кнопку в том числе...картинки завтра запушу

2021-08-13 20:49 UTC, Sunwart requested changes
Мінімальні зауваження, але краще поправити.

2021-08-13 20:49 UTC, Sunwart commented on src/partials/modeling3d.html
> +            <h1 class="modeling__title">3D МОДЕЛЮВАННЯ</h1>
"3D моделювання" пишемо малими, а у великі перетворює стилізація

2021-08-13 20:49 UTC, Sunwart commented on src/partials/modeling3d.html
> +            <div class="hero"></div>
назва класу може потім конфліктувати, краще перейменувати з прив'язкою до modeling

2021-08-13 20:49 UTC, Sunwart commented on src/partials/modeling3d.html
> +            <h3 class="modeling__caption">МИ СТВОРЮЄМО ФОТОРЕАЛІСТИЧНІ
Тут також "Ми" з великої, інше - малими

2021-08-13 20:49 UTC, Sunwart commented on src/partials/modeling3d.html
> +            <button type="submit" class="">ЗРОБИТИ ЗАМОВЛЕННЯ</button>
також прибрати капслок

2021-08-14 08:33 UTC, Vsevolod1001 commented on src/partials/modeling3d.html
> +            <h1 class="modeling__title">3D МОДЕЛЮВАННЯ</h1>
исправлено

2021-08-14 08:33 UTC, Vsevolod1001 commented on src/partials/modeling3d.html
> +            <div class="hero"></div>
исправлено

2021-08-14 08:33 UTC, Vsevolod1001 commented on src/partials/modeling3d.html
> +            <h3 class="modeling__caption">МИ СТВОРЮЄМО ФОТОРЕАЛІСТИЧНІ
исправлено

2021-08-14 08:33 UTC, Vsevolod1001 commented on src/partials/modeling3d.html
> +            <button type="submit" class="">ЗРОБИТИ ЗАМОВЛЕННЯ</button>
исправлено

2021-08-14 08:38 UTC, Sunwart approved these changes
+

2021-08-14 08:39 UTC, merged