Feature/scanning3d - html and images are added
Sunwart/39-team12-freedom3d pull request #21
Opened 2021-08-14 17:40 UTC by SulviY

html added
images added

2021-08-14 20:33 UTC, Sunwart requested changes
момент з кнопкою і з зображеннями - працює одне за всіх :)
Також на сторінці поки не видно зображення з головами.
Юля, якщо хочеш, можеш створито собі з оновленого main нову гілку з іншим ім'ям, перенести все туди і на наступну перевірку відрпавляти вже її, а дану пізніше просто видалимо.

2021-08-14 20:33 UTC, Sunwart commented on src/partials/scanning3d.html
> +    <button type="button"><a class="scanning__link link" href="./order.html">Зробити замовлення</a></button>
Тут в нас лінк, оформлений стилями як кнопка. Але сам тег button не потрібний.

2021-08-14 20:33 UTC, Sunwart commented on src/sass/layout/_scanning3d.scss
> +        background-image: url(../images/scannin3d/mobile_1detail_original-min.png);
Зараз виходить, що одне зображення дублюється на сторінці 4 рази, а інших немає. Треба дописувати.

2021-08-15 15:42 UTC, SulviY commented
тодi цю гiлку можна видалити

2021-08-15 15:42 UTC, SulviY commented on src/partials/scanning3d.html
> +    <button type="button"><a class="scanning__link link" href="./order.html">Зробити замовлення</a></button>
fixed

2021-08-15 15:42 UTC, SulviY commented on src/sass/layout/_scanning3d.scss
> +        background-image: url(../images/scannin3d/mobile_1detail_original-min.png);
fixed

2021-08-15 18:15 UTC, Sunwart commented
зміни внесено в іншій гілці

2021-08-15 18:15 UTC, closed without merging