сделал html разметку для страницы take order
Sunwart/39-team12-freedom3d pull request #6
Opened 2021-08-13 15:22 UTC by ArtemShymanskyi

2021-08-13 19:19 UTC, Sunwart requested changes
треба трошки підправити - прокоментувала код

2021-08-13 19:19 UTC, Sunwart commented on src/partials/ordering.html
> +        <input type="text" name="user-name" minlength="2" placeholder="Ім'я"required pattern="[a-zA-Zа-яёА-ЯЁ]+" title="Имя должно содержать символы кирилицы или латиницы">
Підказку по вводу імені краще написати тією ж мовою, якою весь сайт

2021-08-13 19:19 UTC, Sunwart commented on src/partials/ordering.html
> +        <label>
Не впевнена, але якщо підпису до поля немає, то тег label не потрібний

2021-08-13 19:19 UTC, Sunwart commented on src/partials/ordering.html
> +    <form class="form-order" method="POST" enctype="multipart/form-data">
Клас не описаний в стилях. Просто звертаю увагу, це ок - якщо він тут стоїть на майбутнє.

2021-08-13 19:19 UTC, Sunwart commented on src/partials/ordering.html
> +        </select>
Далі по макету - вибір кольору. Пропущено, треба добавити

2021-08-13 19:19 UTC, Sunwart commented on src/partials/ordering.html
> +    <h2>ТЕЛЕФОНИ</h2>
краще писати з великої букви маленькими літерами, а капслок підключити потім стилями. Те саме - нижче для робочого часу

2021-08-13 19:19 UTC, Sunwart commented on src/partials/ordering.html
> +<a class="footer-mail" href="mailto:3dfreedom.info@gmail.com">3dfreedom.info@gmail.com</a>
не описаний клас footer-mail

2021-08-13 19:19 UTC, Sunwart commented on src/partials/ordering.html
> +<p>Пн-пт: <br>
"пт", "з" і "до" в макеті з великої (хоча це і бісить)

2021-08-13 19:19 UTC, Sunwart commented on src/partials/ordering.html
> +    <h1>Зробити замовлення</h1>
Картинка після заголовку пропущена навмисне?

2021-08-15 19:47 UTC, Sunwart commented
зактира і видалена помилково. Відновлюю

2021-08-16 07:46 UTC, ArtemShymanskyi commented on src/partials/ordering.html
> +    <h1>Зробити замовлення</h1>
так, бо вони всі йдуть фонововими

2021-08-16 11:03 UTC, Sunwart approved these changes
+

2021-08-16 11:03 UTC, merged