Added fonts and styles base
Sunwart/39-team12-freedom3d pull request #8
Opened 2021-08-13 19:09 UTC by wasekw

2021-08-13 20:18 UTC, Sunwart requested changes
Основний момент - прибрати cursor: default; 

Додатково є підозра, що Cera Pro Medium та Caviar Dreams Bold в макеті не використовують, але провіряла поверхнево, тому пропущу так - видалити завжди встигнемо.

2021-08-13 20:18 UTC, Sunwart commented on src/sass/base/_common.scss
> +  cursor: default;
зайве - так курсор при наведенні на лінк буде залишатись стрілкою

2021-08-14 04:41 UTC, wasekw commented on src/sass/base/_common.scss
> +  cursor: default;
ok Удалил.

2021-08-14 07:45 UTC, Sunwart approved these changes
++

2021-08-14 07:45 UTC, merged